name: eapp_dart_domain
description: ethos applications entities and service contracts for dart domain.
version: 2025.07.57
# repository: https://github.com/my_org/my_repo
publish_to: https://dart.pkg.jetbrains.space/50gramx/p/main/dart-delivery/

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  grpc: ^3.0.0
  protobuf: ^3.0.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
